version: "2"
services:
  node:
    build: .docker/node
    user: 1000:1000
    working_dir: "/srv"
    stdin_open: true
    tty: true
    volumes:
      - "./:/srv"
      - "./.docker/node/.cache:/home/node/.cache"
    environment:
      PATH: "/srv/node_modules/.bin:$PATH"
    env_file:
      - .env
  design-system:
    extends:
      service: node
    command: ["lerna", "run", "--scope", "@ellioseven/design-system", "--stream", "start"]
    ports:
      - 4010:4010
